/*
 * ultrasonic.h
 *
 *  Created on: Jul 12, 2022
 *      Author: Mahmoud Yasser
 */
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_


/*******************************************************************************
 *                                  Includes                                   *
 *******************************************************************************/
#include "std_types.h"
#include "gpio.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define Ultrasonic_Trig_PORT_ID                 PORTB_ID
#define Ultrasonic_Trig_PIN_ID                  PIN5_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/





/*
 * Description : Function to initialize the Ultrasonic driver
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void);

/*
 * Description : Function to Trigger the Ultrasonic driver
 * 	1. Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);


/*
 * Description : Function to return the distance in cm from the Ultrasonic sensor
 * 	1. Send the trigger pulse by using Ultrasonic_Trigger function.
 *  2. Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void);



/*
 * Description : Function to calculate the high time generated by the Ultrasonic sensor
 * 	1. Calculate the high time (pulse time) generated by the Ultrasonic sensor
 */

void Ultrasonic_edgeProcessing(void);

#endif
